function dz = dyn2R(z,u,init)
%TEST
%    QDD = TEST(G,L1,L2,M1,M2,ME,T,U1,U2)

g = init.g;
l1 = init.l1;
l2 = init.l2;
m1 = init.m1;
m2 = init.m2;
me = init.me;
u1 = u(1);
u2 = u(2);

% Resolve the input state
th1 = z(1);
th2 = z(2);
dth1 = z(3);
dth2 = z(4);

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    06-Sep-2022 21:38:32

t2 = th1;
t3 = th2;
t4 = l2.*m2;
t7 = l1.^2;
t8 = l2.^2;
t9 = l2.^3;
t11 = m2.^2;
t12 = me.*2.0;
t13 = me.^2;
t16 = -u1;
t5 = cos(t2);
t6 = cos(t3);
t10 = t8.^2;
t14 = dth1;
t15 = dth2;
t17 = -t3;
t18 = m2+t12;
t24 = me.*t4.*t8.*1.2e+1;
t26 = l2.*t4.^2.*3.0;
t28 = m1.*t4.*t7.*1.6e+1;
t29 = l2.*m1.*me.*t7.*4.8e+1;
t32 = m2.*t4.*t7.*4.8e+1;
t33 = me.*t4.*t7.*1.92e+2;
t37 = l2.*t7.*t13.*1.44e+2;
t19 = t14.^2;
t20 = t15.^2;
t21 = g.*l1.*m2.*t5;
t22 = g.*l1.*me.*t5;
t23 = g.*l2.*me.*t6;
t25 = t2+t17;
t34 = (g.*l1.*m1.*t5)./2.0;
t35 = (g.*t4.*t6)./2.0;
t27 = sin(t25);
t30 = -t23;
t31 = cos(t25);
t38 = -t35;
t36 = t31.^2;
t39 = l1.*m2.*t31.*6.0;
t40 = l1.*me.*t31.*1.2e+1;
t41 = l1.*l2.*me.*t4.*t31.*2.4e+1;
t42 = l1.*t4.^2.*t31.*1.2e+1;
t51 = (l1.*l2.*t18.*t19.*t27)./2.0;
t52 = (l1.*l2.*t18.*t20.*t27)./2.0;
t43 = -t41;
t44 = -t42;
t45 = m2.*t4.*t7.*t36.*3.6e+1;
t46 = me.*t4.*t7.*t36.*1.44e+2;
t48 = t36.*t37;
t50 = l2.*t7.*t13.*t36.*-1.44e+2;
t53 = t4+t39+t40;
t54 = t30+t38+t51+u2;
t55 = t16+t21+t22+t34+t52;
t47 = -t45;
t49 = -t46;
t56 = t24+t26+t28+t29+t32+t33+t37+t43+t44+t47+t49+t50;
t57 = 1.0./t56;
mt1 = [t53.*t57.*(t23+t35-t51-u2).*1.2e+1-(t55.*(m2+me.*3.0).*4.8e+1)./(t7.*t11.*4.8e+1+t7.*t13.*1.44e+2+t4.^2.*3.0+l2.*me.*t4.*1.2e+1+m1.*m2.*t7.*1.6e+1+m1.*me.*t7.*4.8e+1+m2.*me.*t7.*1.92e+2-t7.*t11.*t36.*3.6e+1-t7.*t13.*t36.*1.44e+2-l1.*m2.*t4.*t31.*1.2e+1-l1.*me.*t4.*t31.*2.4e+1-m2.*me.*t7.*t36.*1.44e+2)];
mt2 = [t53.*t55.*t57.*1.2e+1-((l2.*t4+m1.*t7.*4.0+m2.*t7.*1.2e+1+me.*t7.*1.2e+1).*(t23+t35-t51-u2).*1.2e+1)./(l2.*t28+l2.*t33+t4.^2.*t7.*4.8e+1+t4.^2.*t8.*3.0-t4.^2.*t7.*t36.*3.6e+1+me.*t4.*t9.*1.2e+1+t7.*t8.*t13.*1.44e+2+m1.*me.*t7.*t8.*4.8e+1-t7.*t8.*t13.*t36.*1.44e+2-l1.*l2.*t4.^2.*t31.*1.2e+1-l1.*me.*t4.*t8.*t31.*2.4e+1-l2.*me.*t4.*t7.*t36.*1.44e+2)];
qdd = [mt1;mt2];

% Return in state-space form, i.e., qdot, qddot
dz = [z(3:4);qdd];
